[package]
name = "doc-test-0_19"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
alloy-primitives = "0.4"
alloy-sol-types = "0.4"
anyhow = "1.0"
bonsai-ethereum-relay = { git = "https://github.com/risc0/risc0.git", branch = "release-0.19" }
clap = { version = "4.1", features = ["derive", "env"] }
ethers = { version = "2.0", features = ["rustls", "ws"] }
fibonacci-methods = { git = "https://github.com/risc0/risc0.git", branch = "release-0.19" }
risc0-zkvm = { git = "https://github.com/risc0/risc0.git", branch = "release-0.19", features = [
  "prove",
] }
risc0-zkvm-methods = { git = "https://github.com/risc0/risc0.git", branch = "release-0.19" }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full", "sync"] }

[build-dependencies]
glob = "0.3"

[features]
metal = ["risc0-zkvm/metal"]
