name: website

on:
  merge_group:
  pull_request:
    branches: [main, "release-*"]
    paths:
      - "website/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: npx prettier website --check
      - run: python website/github-link-version-check.py
