[package]
name = "bonsai-sdk"
description = "Bonsai Software Development Kit"
version = "0.6.0-rc.1"
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
reqwest = { version = "0.11", default-features = false, features = [
  "blocking",
  "json",
  "rustls-tls",
] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
tokio = { version = "1", features = ["full", "sync"], optional = true }

[dev-dependencies]
httpmock = "0.6"
temp-env = "0.3"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1.3", features = ["v4"] }

[lib]
# Disables the doctest from the README because it imports external components and make requests
doctest = false

[features]
default = ["std"]
std = []
async = ["dep:tokio"]
